import AppKit

/// Reads what was just copied off a pasteboard, or says why it is not to be kept, and
/// puts a kept copy back.
///
/// Nothing on the pasteboard is read until the privacy rules have had their say, and
/// those look only at what the copy is marked as and where it came from: a copy an app
/// marks as not for keeping, or one made while a password manager was in front, is
/// never read. A password manager that marks nothing, working through a browser
/// extension, looks like the browser; those are what the markers are for.
@MainActor
enum ClipboardReader {
    /// What reading found.
    enum Reading: Equatable {
        /// Ready to go into the history.
        case content(ClipboardContent, source: ClipboardSource?)
        /// A picture, whose kept copy is still to be made (`ClipboardImage.make`), off
        /// the main thread.
        case picture(Data, type: NSPasteboard.PasteboardType, source: ClipboardSource?)
        case skipped(Skip)
    }

    enum Skip: Equatable {
        /// Marked by the app that copied it as not for keeping.
        case marked
        /// Copied from a password manager.
        case passwordManager
        /// Nothing the history keeps: whitespace, a colour, an app's private data.
        case nothingKept
        /// Longer than the history keeps (`ClipboardLimits`).
        case tooLarge
        /// A picture copied on an iPhone or iPad, still on the device.
        case remotePicture
    }

    // MARK: Privacy

    /// Types an app adds to say what it copied is not for keeping, after the
    /// conventions at nspasteboard.org: a password or other secret, something on the
    /// clipboard only for a moment (text a utility pastes for you), or something the
    /// app made up rather than the person copied. The rest are older or app-specific
    /// spellings of the same request that apps still write.
    static let markers = Set([
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // 1Password 7 marks what it copies with this alone.
        "com.agilebits.onepassword",
        // The transient type before nspasteboard.org took it over.
        "de.petermaurer.TransientPasteboardType",
        // TypeIt4Me's snippets, on the clipboard only to be pasted.
        "com.typeit4me.clipping",
        // KeeWeb, the password manager.
        "net.antelle.keeweb",
        // An older transient marker some utilities still write, which other clipboard
        // managers leave alone too.
        "Pasteboard generator type",
    ].map { NSPasteboard.PasteboardType($0) })

    /// The nspasteboard.org markers as apps built on other toolkits spell them. Qt
    /// passes the MIME type KeePassXC writes, `application/x-nspasteboard-concealed-type`,
    /// through as `com.trolltech.anymime.application--x-nspasteboard-concealed-type`, so
    /// a type ending in one of these is a marker whatever comes before it.
    static let markerEndings = [
        "nspasteboard-concealed-type",
        "nspasteboard-transient-type",
        "nspasteboard-autogenerated-type",
    ]

    static func isMarker(_ type: NSPasteboard.PasteboardType) -> Bool {
        if markers.contains(type) { return true }
        let raw = type.rawValue.lowercased()
        return markerEndings.contains { raw.hasSuffix($0) }
    }

    /// What Universal Clipboard puts beside something copied on another device. The
    /// copy itself stays on the device until it is read, and reading it fetches it.
    static let remoteMarker = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")

    /// Where an app that copies on someone's behalf (a clipboard tool, a launcher) says
    /// which app it is, after nspasteboard.org: the bundle identifier, as text.
    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// Password managers, by bundle identifier. An entry ending in a dot covers every
    /// app under it: each version's own identifier, and its helpers and menu bar
    /// extras. Whatever they copy is left alone, marked or not. Apple's Passwords
    /// appears to mark nothing, so a copy from its menu bar extra is caught only if the
    /// extra has come to the front.
    static let passwordManagers: [String] = [
        "com.1password.",           // 1Password 8 and its helpers
        "com.agilebits.",           // 1Password 7 and before, which AgileBits made alone
        "com.bitwarden.",
        "com.apple.keychainaccess",
        "com.apple.Passwords",      // Passwords, and its menu bar extra
        "com.dashlane.",
        "com.lastpass.",
        "org.keepassxc.",
        "in.sinew.",                // Enpass, whose Mac app is in.sinew.Enpass-Desktop
        "com.markmcguill.strongbox",
        "me.proton.pass",
        "com.nordsec.nordpass",
    ]

    static func isPasswordManager(_ bundleIdentifier: String?) -> Bool {
        guard let id = bundleIdentifier?.lowercased(), !id.isEmpty else { return false }
        return passwordManagers.contains { entry in
            let entry = entry.lowercased()
            return entry.hasSuffix(".") ? id.hasPrefix(entry) : id == entry || id.hasPrefix(entry + ".")
        }
    }

    // MARK: Reading

    /// Picture types kept, best first. TIFF last: most apps put a PNG beside it, and a
    /// TIFF alone is kept as a PNG.
    static let pictureTypes: [NSPasteboard.PasteboardType] = [
        .png, NSPasteboard.PasteboardType("public.jpeg"), NSPasteboard.PasteboardType("public.heic"),
        NSPasteboard.PasteboardType("com.compuserve.gif"), .tiff,
    ]

    /// Reads what is on `pasteboard`. `frontmost` is the app in front as the copy was
    /// noticed, taken as its source unless the copy names another. `alsoInFront` is
    /// every app that came to the front since the pasteboard was last looked at: the
    /// copy was made by one of them, and a password copied a moment before Cmd-Tab
    /// brings the app it is for to the front must still count as the password
    /// manager's.
    ///
    /// Files come first, since Finder puts their names and icons beside them; then
    /// text, since formatted text often carries a picture of itself (Numbers' cells,
    /// Office's paragraphs), which is not what was copied; then a picture; and a link
    /// last. A picture copied from a browser comes with its address, as text or as a
    /// link, and is the picture, not the address.
    static func read(_ pasteboard: NSPasteboard, frontmost: ClipboardSource?, alsoInFront: [String?] = []) -> Reading {
        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty else { return .skipped(.nothingKept) }
        guard !types.contains(where: isMarker) else { return .skipped(.marked) }

        var declared: ClipboardSource?
        if types.contains(sourceType),
           let id = pasteboard.string(forType: sourceType)?.trimmingCharacters(in: .whitespacesAndNewlines) {
            declared = ClipboardSource(installedApp: id)
        }
        // Any app that might have made the copy rules it out: the one it names, and
        // every one in front around it. A named source decides only where it is shown
        // to have come from.
        let suspects = [declared?.bundleIdentifier, frontmost?.bundleIdentifier] + alsoInFront
        guard !suspects.contains(where: isPasswordManager) else { return .skipped(.passwordManager) }
        let source = declared ?? frontmost

        if types.contains(.fileURL) {
            let urls = (pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
            if !urls.isEmpty { return .content(.files(urls), source: source) }
        }

        let pictureType = pictureTypes.first(where: types.contains)
        var link: URL?

        if types.contains(.string), let text = pasteboard.string(forType: .string) {
            if text.utf16.count > ClipboardLimits.textLength { return .skipped(.tooLarge) }
            if !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                link = Self.link(in: text)
                if link == nil { return .content(.text(text), source: source) }
            }
        }
        if link == nil, types.contains(.URL), let string = pasteboard.string(forType: .URL) {
            link = Self.link(in: string)
        }

        if let pictureType {
            // A photo from an iPhone can take seconds to come across, all of them on the
            // main thread, while the island stands still. Its text comes quickly enough.
            guard !types.contains(remoteMarker) else { return .skipped(.remotePicture) }
            guard let data = pasteboard.data(forType: pictureType), !data.isEmpty else { return .skipped(.nothingKept) }
            // TIFF is re-encoded before its size is judged; anything else is kept as is.
            let limit = pictureType == .tiff ? ClipboardLimits.tiffBytes : ClipboardLimits.pictureBytes
            guard data.count <= limit else { return .skipped(.tooLarge) }
            return .picture(data, type: pictureType, source: source)
        }

        if let link {
            let title = pasteboard.string(forType: urlName).flatMap(nonEmpty)
            return .content(.link(link, title: title), source: source)
        }
        return .skipped(.nothingKept)
    }

    /// The link's title, next to `public.url`.
    static let urlName = NSPasteboard.PasteboardType("public.url-name")

    /// Text that is a web or mail address and nothing else: a link copied from the
    /// address bar or a message, kept as a link rather than as text.
    static func link(in text: String) -> URL? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, trimmed.count <= 4096,
              trimmed.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
              let url = URL(string: trimmed),
              let scheme = url.scheme?.lowercased()
        else { return nil }
        switch scheme {
        case "http", "https": return url.host()?.isEmpty == false ? url : nil
        case "mailto": return trimmed.count > 7 ? url : nil
        default: return nil
        }
    }

    private static func nonEmpty(_ string: String) -> String? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    // MARK: Writing

    /// Puts a kept copy back on `pasteboard` as the thing most recently copied, and
    /// returns whether it went. A link goes as a link and as its address in text, so it
    /// pastes into a browser and into a text field alike.
    @discardableResult
    static func write(_ content: ClipboardContent, to pasteboard: NSPasteboard) -> Bool {
        pasteboard.clearContents()
        switch content {
        case .text(let text):
            return pasteboard.setString(text, forType: .string)
        case .link(let url, let title):
            let item = NSPasteboardItem()
            item.setString(url.absoluteString, forType: .URL)
            item.setString(url.absoluteString, forType: .string)
            if let title { item.setString(title, forType: urlName) }
            return pasteboard.writeObjects([item])
        case .image(let image):
            return pasteboard.setData(image.data, forType: image.type)
        case .files(let urls):
            return pasteboard.writeObjects(urls.map { $0 as NSURL })
        }
    }
}

/// How much the history keeps of any one copy.
enum ClipboardLimits {
    /// Text longer than this, in UTF-16 units (a little over 100,000 characters of
    /// English), is left out rather than cut short, so whatever is put back is exactly
    /// what was copied.
    static let textLength = 100_000
    /// A picture's bytes, as kept. Larger ones are left out.
    static let pictureBytes = 20 * 1024 * 1024
    /// Every picture's bytes together. Past this, the oldest unpinned pictures go
    /// first, so a run of large screenshots cannot swell Islet to hundreds of
    /// megabytes.
    static let allPicturesBytes = 80 * 1024 * 1024
    /// A TIFF's bytes before it is re-encoded as PNG. A Retina screenshot is about 24 MB.
    static let tiffBytes = 96 * 1024 * 1024
    /// The largest picture written to disk with the history kept between launches;
    /// larger ones are kept only while Islet runs, unless pinned.
    static let savedPictureBytes = 2 * 1024 * 1024
    /// The characters of a text shown in a row. The rest is kept, just not laid out.
    static let previewLength = 400
}
